apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "coordinate-service.fullname" . }}
  labels:
    {{- include "coordinate-service.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "coordinate-service.selectorLabels" . | nindent 6 }}
