apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coordinate-service.fullname" . }}
  labels:
    {{- include "coordinate-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-connection: {{ .Values.secrets.postgresConnection | quote }}
