environment: Staging

replicaCount: 2

ingress:
  enabled: true
  className: nginx
  host: coordinates.stage.example.com

networkPolicy:
  enabled: true

secrets:
  postgresConnection: "Host=psql-stage;Port=5432;Database=coordinates;Username=app;Password=changeme"
